# Generated by Django 4.0.1 on 2022-05-21 00:16

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_goalcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', related_query_name='goals', to='goals.goalcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=django.contrib.postgres.indexes.HashIndex(fields=['user'], name='goals_goal_user_id_75da70_hash'),
        ),
        migrations.AddIndex(
            model_name='goalcategory',
            index=django.contrib.postgres.indexes.HashIndex(fields=['user'], name='goals_goalc_user_id_af3bf9_hash'),
        ),
        migrations.AddIndex(
            model_name='goalcomment',
            index=django.contrib.postgres.indexes.HashIndex(fields=['user'], name='goals_goalc_user_id_9e46cc_hash'),
        ),
    ]
