services:
  api:
    image: test:latest
    volumes:
      - ./..:/code
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_DB: "$DB_NAME"
  migrations:
    image: test:latest